[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
ffi = false
fs_permissions = [
    { access = "read-write", path = "./broadcast" },
    { access = "read", path = "./img/" },
    { access = "read", path = "./test" },
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
